name = "aiostreams-cloudflare-worker"
main = "src/index.js"
compatibility_date = "2024-12-02"
workers_dev = true
preview_urls = true
compatibility_flags = [ "nodejs_compat" ]
[observability.logs]
enabled = true